[package]
name = "rtimer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.15.2"
chrono = "0.4"
cli-clipboard = "0.3.0"

[build-dependencies]
winres = "0.1"